routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin');
});

Route::resource('/countries', 'CountryController');
Route::resource('/eventCategories', 'EventCategoryController');

app/Country.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    protected $table = 'countries';
}

app/EventCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EventCategory extends Model
{
    protected $table = 'event_categories';
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CountryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Country;

class CountryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $countries = Country::all();
        return view('countries.index', array('countryList' =>$countries));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $countries = Country::all();
        return view('countries.create', array('countryList' =>$countries));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'code'=> 'required',
        ]);
        $country = new Country;
        $country->name = $request->name;
        $country->code = $request->code;
        $country->save();
        return redirect('/countries')->with('success', 'country has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $country = Country::find($id);
        $countrylist = Country::all();
        
        return view('countries.show', array('country' => $country));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $country = Country::find($id);
        $countryList = Country::all();
        return view('countries.edit', compact('country', 'countryList'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
            'code'=> 'required',
        ]);

        $country = Country::find($id);
        $country->name = $request->get('name');
        $country->code = $request->get('code');
     
        $country->save();

        return redirect('countries')->with('success', 'updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $country = Country::find($id);
        $country->delete();
        
        return redirect('countries');
    }
}

app/Http/Controllers/EventCategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\EventCategory;

class EventCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $eventCategories = EventCategory::all();
        return view('eventCategories.index', array('eventCategoryList' =>$eventCategories));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $eventCategories = EventCategory::all();
        return view('eventCategories.create', array('eventCategoryList' =>$eventCategories));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
        ]);
        $eventCategory = new EventCategory;
        $eventCategory->name = $request->name;
        $eventCategory->save();
        return redirect('/eventCategories')->with('success', 'eventCategory has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $eventCategory = EventCategory::find($id);
        $eventCategoryList = EventCategory::all();
        
        return view('eventCategories.show', array('eventCategory' => $eventCategory));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $eventCategory = EventCategory::find($id);
        $eventCategoryList = EventCategory::all();
        return view('eventCategories.edit', compact('eventCategory', 'eventCategoryList'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
        ]);

        $eventCategory = EventCategory::find($id);
        $eventCategory->name = $request->get('name');
     
        $eventCategory->save();

        return redirect('eventCategories')->with('success', 'updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $eventCategory = EventCategory::find($id);
        $eventCategory->delete();
        
        return redirect('eventCategories');
    }
}

resources/views/admin.blade.php
<!DOCTYPE html>
<html lang="nl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="author" content="Ben Dierckx">
    <link rel="stylesheet" href="{{ secure_asset('css/fricfrac.css') }}" type="text/css"/>
    <title>Beheer Fric-Frac</title>
</head>
<body>
    <header>
        <h1>Fric-Frac</h1>
    </header>
    <main>
        <section>
            <!-- a.tile[id]*11 -->
            <a href="Person/Index.php" class="tile" id=""><span>Persoon</span></a>
            <a href="{{route('countries.index')}}" class="tile" id=""><span>Land</span></a>
            <a class="tile" id=""></a>
            <a class="tile" id=""></a>
            <a href="Role/Index.php" class="tile" id=""><span>Role</span></a>
            <a href="User/Index.php" class="tile" id=""><span>Gebruiker</span></a>
            <a class="tile" id=""></a>
            <a href="Event/Index.php" class="tile" id=""><span>Event</span></a>
            <a href="{{route('eventCategories.index')}}" class="tile" id=""><span>Event Categorie</span></a>
            <a href="EventTopic/Index.php" class="tile" id=""><span>Event Topic</span></a>
            <a class="tile" id=""></a>
        </section>
    </main>
    <footer>
        <p>CVO Antwerpen 2018-2019 Fric-Frac</p>
    </footer>
</body>
</html>

resources/views/countries/create.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="author" content="Ben Dierckx">
    <link rel="stylesheet" href="{{ asset('css/fricfrac.css') }}" type="text/css"/>
    <title>Fric-Frac</title>
  </head>
  <body>
    <main>
      <article>
        <header>
          <h2>Land</h2>
          <nav>
            <a href="{{route('countries.index')}}">Annuleren</a>
          </nav>
        </header>
        <form method="post" action="{{ route('countries.store') }}">
          <div class="form-group">
            @csrf
            <label for="name">Name:</label>
            <input type="text" class="form-control" name="name"/>
          </div>
          <div class="form-group">
            <label for="code">code :</label>
            <input type="text" class="form-control" name="code"/>
          </div>
          <button type="submit" class="btn btn-primary">Add</button>
        </form>
      </article>
      @include('countries.readingAll')
  </main>
</body>
</html>

resources/views/countries/edit.blade.php
<?php //edit = updateone ?>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="author" content="Ben Dierckx">
    <link rel="stylesheet" href="{{ asset('css/fricfrac.css') }}" type="text/css"/>
    <title>Fric-Frac</title>
  </head>
  <body>
    <main>
        <article>
          <header>
              <h2>Land</h2>
          <nav>
             <a href="{{route('countries.index')}}">Annuleren</a>
          </nav>
          </header>
          <form method="post" action="{{ route('countries.update', $country->id) }}">
              @method('PATCH')
              @csrf
              <div>
                <label for="name">Name:</label>
                <input type="text"  name="name" value="{{ $country->name }}" />
              </div>
              <div>
                <label for="code">code :</label>
                <input type="text" name="code" value="{{ $country->code }}" />
              </div>
              
              <button type="submit">Update</button>
          </form>
        </article>
        @include('countries.readingAll')
    </main>
  </body>
</html>

resources/views/countries/index.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="author" content="Ben Dierckx">
        <link rel="stylesheet" href="{{ asset('css/fricfrac.css') }}" type="text/css"/>
        <title>Fric-Frac</title>
    </head>
    <body>
        <main>
            <article>
                <header>
                    <h2>Land</h2>
                        <nav>
                            <a href="{{route('countries.create')}}">Create</a>
                        </nav>
                </header>
                <nav>
                    <fieldset>
                        <div>
                        </div>
                    </fieldset>
                </nav>
            </article>
            @include('countries.readingAll')
        </main>
    </body>
</html>

resources/views/countries/readingAll.blade.php
<aside>
    <table>
        <thead>
            <tr>
                <td>select</td>
                <td>Name</td>
                <td>Code</td>
            </tr>
        </thead>
        <tbody>
            @foreach($countryList as $country) 
            <tr>
                <td><a href="{{ route('countries.show',$country->id)}}">show</a></td>
                <td>{{$country->name}}</td>
                <td>{{$country->code}}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
</aside>

resources/views/countries/show.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="author" content="Ben Dierckx">
    <link rel="stylesheet" href="{{ asset('css/fricfrac.css') }}" type="text/css"/>
    <title>Fric-Frac</title>
  </head>
  <body>
    <main>
      <article>
        <header>
    			<h2>Land</h2>
    			<nav>
    				<a href="{{route('countries.edit', ['id' => $country->id])}}">Edit</a>
    				<a href="{{route('countries.create')}}">Create</a>
    				<button type="submit" value="delete" form="form">Delete</button>
    				<a href="{{route('countries.index')}}">Annuleren</a>
    			</nav>
    		</header>
        <form action="{{ route('countries.destroy', ['id' => $country->id])}}" id="form" method="post">
          @csrf
          @method('DELETE')
    			<div>
    				<label for="Name">Naam</label>
    				<input type="text" readonly id="Name" name="name" value="{{$country->name}}">
    			</div>
    			<div>
    				<label for="Code">Code</label>
    				<input type="text" readonly id="Code" name="countryCode" value="{{$country->code}}">
    			</div>
        </form>
        <a href={{route('countries.index')}}>index</a>
      </article>
    </main>
  </body>
</html>

resources/views/eventCategories/create.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="author" content="Ben Dierckx">
    <link rel="stylesheet" href="{{ asset('css/fricfrac.css') }}" type="text/css"/>
    <title>Fric-Frac</title>
  </head>
  <body>
    <main>
      <article>
        <header>
          <h2>EventCategory</h2>
          <nav>
            <a href="{{route('eventCategories.index')}}">Annuleren</a>
          </nav>
        </header>
        <form method="post" action="{{ route('eventCategories.store') }}">
          <div class="form-group">
            @csrf
            <label for="name">Name:</label>
            <input type="text" class="form-control" name="name"/>
          </div>
          <button type="submit" class="btn btn-primary">Add</button>
        </form>
      </article>
      @include('eventCategories.readingAll')
  </main>
</body>
</html>

resources/views/eventCategories/edit.blade.php
<?php //edit = updateone ?>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="author" content="Ben Dierckx">
    <link rel="stylesheet" href="{{ asset('css/fricfrac.css') }}" type="text/css"/>
    <title>Fric-Frac</title>
  </head>
  <body>
    <main>
        <article>
          <header>
              <h2>EventCategory</h2>
          <nav>
             <a href="{{route('eventCategories.index')}}">Annuleren</a>
          </nav>
          </header>
          <form method="post" action="{{ route('eventCategories.update', $eventCategory->id) }}">
              @method('PATCH')
              @csrf
              <div>
                <label for="name">Name:</label>
                <input type="text"  name="name" value="{{ $eventCategory->name }}" />
              </div>
              
              <button type="submit">Update</button>
          </form>
        </article>
        @include('eventCategories.readingAll')
    </main>
  </body>
</html>

resources/views/eventCategories/index.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="author" content="Ben Dierckx">
        <link rel="stylesheet" href="{{ asset('css/fricfrac.css') }}" type="text/css"/>
        <title>Fric-Frac</title>
    </head>
    <body>
        <main>
            <article>
                <header>
                    <h2>EventCategory</h2>
                        <nav>
                            <a href="{{route('eventCategories.create')}}">Create</a>
                        </nav>
                </header>
                <nav>
                    <fieldset>
                        <div>
                        </div>
                    </fieldset>
                </nav>
            </article>
            @include('eventCategories.readingAll')
        </main>
    </body>
</html>

resources/views/eventCategories/readingAll.blade.php
<aside>
    <table>
        <thead>
            <tr>
                <td>select</td>
                <td>Name</td>
            </tr>
        </thead>
        <tbody>
            @foreach($eventCategoryList as $eventCategory) 
            <tr>
                <td><a href="{{ route('eventCategories.show',$eventCategory->id)}}">show</a></td>
                <td>{{$eventCategory->name}}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
</aside>

resources/views/eventCategories/show.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="author" content="Ben Dierckx">
    <link rel="stylesheet" href="{{ asset('css/fricfrac.css') }}" type="text/css"/>
    <title>Fric-Frac</title>
  </head>
  <body>
    <main>
      <article>
        <header>
    			<h2>EventCategory</h2>
    			<nav>
    				<a href="{{route('eventCategories.edit', ['id' => $eventCategory->id])}}">Edit</a>
    				<a href="{{route('eventCategories.create')}}">Create</a>
    				<button type="submit" value="delete" form="form">Delete</button>
    				<a href="{{route('eventCategories.index')}}">Annuleren</a>
    			</nav>
    		</header>
        <form action="{{ route('eventCategories.destroy', ['id' => $eventCategory->id])}}" id="form" method="post">
          @csrf
          @method('DELETE')
    			<div>
    				<label for="Name">Naam</label>
    				<input type="text" readonly id="Name" name="name" value="{{$eventCategory->name}}">
    			</div>
        </form>
        <a href={{route('eventCategories.index')}}>index</a>
      </article>
    </main>
  </body>
</html>